db:
  source: jdbc
  connection:
    url: jdbc:postgresql://localhost:5432/distribuida
    username: postgres
    password: 12345
  statements:
    ping: "DO 0"
    find-one: "select isbn from books WHERE id = :id"
    find-all: "select isbn from Books"
    insert-one: "insert into books (author_id, isbn, title, price) VALUES(:authorId, :isbn, :title, :price)"